trigger:
  branches:
    include:
      - develop

pool:
  name: 'SelfHosted'

variables:
  - group: 'tpfinal-vars'

jobs:
  - job: BuildFront
    displayName: 'Build et publication du front Vue.js'
    steps:
      - template: templates/_build-front.yml